
import java.io.FileNotFoundException;
import java.text.ParseException;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aditiambadkar
 */
public class TeacherUploadAssignments extends javax.swing.JFrame {

    /**
     * Creates new form TeacherUploadAssignments
     */
    public TeacherUploadAssignments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        UpperPanel = new javax.swing.JPanel();
        SubmitAssignmentLabel = new javax.swing.JLabel();
        LowerPanel = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        AssignmentIdLabel = new javax.swing.JLabel();
        AssignmentIdTextArea = new javax.swing.JTextField();
        AssignmentNameLabel = new javax.swing.JLabel();
        SubmissionDateTextArea = new javax.swing.JTextField();
        SubmissionDateLabel = new javax.swing.JLabel();
        AssignmentNameTextArea = new javax.swing.JTextField();
        UploadFilePathLabel = new javax.swing.JLabel();
        FilePathTextArea = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NoteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        UpperPanel.setBackground(new java.awt.Color(167, 167, 231));

        SubmitAssignmentLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        SubmitAssignmentLabel.setForeground(new java.awt.Color(255, 255, 255));
        SubmitAssignmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubmitAssignmentLabel.setText("Upload your assignments here");

        javax.swing.GroupLayout UpperPanelLayout = new javax.swing.GroupLayout(UpperPanel);
        UpperPanel.setLayout(UpperPanelLayout);
        UpperPanelLayout.setHorizontalGroup(
            UpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpperPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubmitAssignmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        UpperPanelLayout.setVerticalGroup(
            UpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(SubmitAssignmentLabel)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        LowerPanel.setBackground(new java.awt.Color(167, 167, 231));

        BackButton.setBackground(new java.awt.Color(255, 255, 255));
        BackButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(0, 0, 51));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LowerPanelLayout = new javax.swing.GroupLayout(LowerPanel);
        LowerPanel.setLayout(LowerPanelLayout);
        LowerPanelLayout.setHorizontalGroup(
            LowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowerPanelLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LowerPanelLayout.setVerticalGroup(
            LowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        AssignmentIdLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        AssignmentIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AssignmentIdLabel.setText("Enter Assignment ID:");

        AssignmentIdTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignmentIdTextAreaActionPerformed(evt);
            }
        });

        AssignmentNameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        AssignmentNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AssignmentNameLabel.setText("Enter Assignment Name:");

        SubmissionDateTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmissionDateTextAreaActionPerformed(evt);
            }
        });

        SubmissionDateLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SubmissionDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SubmissionDateLabel.setText("Enter Submission Date: ");

        AssignmentNameTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignmentNameTextAreaActionPerformed(evt);
            }
        });

        UploadFilePathLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UploadFilePathLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UploadFilePathLabel.setText("Upload file path:");

        FilePathTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilePathTextAreaActionPerformed(evt);
            }
        });

        SubmitButton.setBackground(new java.awt.Color(255, 255, 255));
        SubmitButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(0, 0, 51));
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("NOTE: (yyyy-mm-dd)");

        NoteLabel.setText("NOTE: AssignmentID format : subject Id+assignment Id");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(NoteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AssignmentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmissionDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubmissionDateTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssignmentNameTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addContainerGap(121, Short.MAX_VALUE)
                                .addComponent(AssignmentIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(UploadFilePathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AssignmentIdTextArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FilePathTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(UpperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssignmentIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssignmentIdTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssignmentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssignmentNameTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmissionDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmissionDateTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UploadFilePathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FilePathTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SubmitButton)
                .addGap(18, 18, 18)
                .addComponent(LowerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        TeacherLoginPage teacherlogin=new TeacherLoginPage();
        teacherlogin.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        if(AssignmentIdTextArea.getText().isEmpty() || AssignmentNameTextArea.getText().isEmpty() || SubmissionDateTextArea.getText().isEmpty() || FilePathTextArea.getText().isEmpty())
        {
            AssignmentIdTextArea.setText("");
            AssignmentNameTextArea.setText("");
            SubmissionDateTextArea.setText("");
            FilePathTextArea.setText("");
            JOptionPane.showMessageDialog(this,"Fields cannot be empty!!","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            int flag = 0;
            int flag1=0;
            try 
            {
                int checkAssignmentId=Integer.parseInt(AssignmentIdTextArea.getText());
                boolean checkDate;
                if(!SubmissionDateTextArea.getText().matches("([0-9]{4})-([0-9]{2})-([0-9]{2})"))
                {
                    throw new IllegalArgumentException();
                            
                         
                }
                flag = LoginFrame.op.uploadAssignmentTeacher(AssignmentIdTextArea.getText(),AssignmentNameTextArea.getText(),SubmissionDateTextArea.getText(),FilePathTextArea.getText());
                if(flag!=0)
            {
                JOptionPane.showMessageDialog(this,"Assignment uploaded successfully!!","Success",JOptionPane.ERROR_MESSAGE);
                AssignmentIdTextArea.setText("");
                AssignmentNameTextArea.setText("");
                SubmissionDateTextArea.setText("");
                FilePathTextArea.setText("");
            }
                         
            }
                   
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this,"Assignment Id is numeric value!!","Error",JOptionPane.ERROR_MESSAGE);
                TeacherUploadAssignments teacheruploadFrame = new TeacherUploadAssignments();
                teacheruploadFrame.setVisible(true);
                this.setVisible(false);
                dispose();

            }
            catch(ParseException e)
            {
                JOptionPane.showMessageDialog(this,"Invalid Date format!!","Error",JOptionPane.ERROR_MESSAGE);
                TeacherUploadAssignments teacheruploadFrame = new TeacherUploadAssignments();
                teacheruploadFrame.setVisible(true);
                this.setVisible(false);
                dispose();
            }
            catch(FileNotFoundException e){
                JOptionPane.showMessageDialog(this,"Incorrect file path!!","Error",JOptionPane.ERROR_MESSAGE);
                TeacherUploadAssignments teacheruploadFrame = new TeacherUploadAssignments();
                teacheruploadFrame.setVisible(true);
                this.setVisible(false);
                dispose();

            }
            catch(IllegalArgumentException e)
            {
                 JOptionPane.showMessageDialog(this,"Date should be in yyyy-mm-dd format","Error",JOptionPane.ERROR_MESSAGE);
                 SubmissionDateTextArea.setText("");  
            }
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void AssignmentIdTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignmentIdTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssignmentIdTextAreaActionPerformed

    private void SubmissionDateTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmissionDateTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmissionDateTextAreaActionPerformed

    private void AssignmentNameTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignmentNameTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssignmentNameTextAreaActionPerformed

    private void FilePathTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilePathTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilePathTextAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherUploadAssignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherUploadAssignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherUploadAssignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherUploadAssignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherUploadAssignments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AssignmentIdLabel;
    private javax.swing.JTextField AssignmentIdTextArea;
    private javax.swing.JLabel AssignmentNameLabel;
    private javax.swing.JTextField AssignmentNameTextArea;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField FilePathTextArea;
    private javax.swing.JPanel LowerPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NoteLabel;
    private javax.swing.JLabel SubmissionDateLabel;
    private javax.swing.JTextField SubmissionDateTextArea;
    private javax.swing.JLabel SubmitAssignmentLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel UploadFilePathLabel;
    private javax.swing.JPanel UpperPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
