
import java.sql.Date;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import sun.swing.table.DefaultTableCellHeaderRenderer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chetana
 */
public class TeacherLoginPage extends javax.swing.JFrame {

    /**
     * Creates new form TeacherLoginPage
     */
    public TeacherLoginPage() {
        initComponents();
        displayTeacherInformation();
        displaySubmittedAssignments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        UpperPanel = new javax.swing.JPanel();
        TeacherNameLabel = new javax.swing.JLabel();
        UploadSolutionPanel = new javax.swing.JPanel();
        LogoutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AssignmentListTable = new javax.swing.JTable();
        UploadSolutionButton = new javax.swing.JButton();
        UploadAssignmentButton = new javax.swing.JButton();
        CheckAssignmentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        UpperPanel.setBackground(new java.awt.Color(167, 167, 231));

        TeacherNameLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        TeacherNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        TeacherNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TeacherNameLabel.setText("teacher name");

        javax.swing.GroupLayout UpperPanelLayout = new javax.swing.GroupLayout(UpperPanel);
        UpperPanel.setLayout(UpperPanelLayout);
        UpperPanelLayout.setHorizontalGroup(
            UpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(TeacherNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        UpperPanelLayout.setVerticalGroup(
            UpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(TeacherNameLabel)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        UploadSolutionPanel.setBackground(new java.awt.Color(167, 167, 231));

        LogoutButton.setBackground(new java.awt.Color(255, 255, 255));
        LogoutButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(0, 0, 51));
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UploadSolutionPanelLayout = new javax.swing.GroupLayout(UploadSolutionPanel);
        UploadSolutionPanel.setLayout(UploadSolutionPanelLayout);
        UploadSolutionPanelLayout.setHorizontalGroup(
            UploadSolutionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UploadSolutionPanelLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UploadSolutionPanelLayout.setVerticalGroup(
            UploadSolutionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UploadSolutionPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addContainerGap())
        );

        AssignmentListTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AssignmentListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Assignment No", "Assignment Name", "Student Id", "Student Name"
            }
        ));
        jScrollPane1.setViewportView(AssignmentListTable);

        UploadSolutionButton.setBackground(new java.awt.Color(255, 255, 255));
        UploadSolutionButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        UploadSolutionButton.setForeground(new java.awt.Color(0, 0, 51));
        UploadSolutionButton.setText("Upload Solution");
        UploadSolutionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadSolutionButtonActionPerformed(evt);
            }
        });

        UploadAssignmentButton.setBackground(new java.awt.Color(255, 255, 255));
        UploadAssignmentButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        UploadAssignmentButton.setForeground(new java.awt.Color(0, 0, 51));
        UploadAssignmentButton.setText("Upload Assignment");
        UploadAssignmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadAssignmentButtonActionPerformed(evt);
            }
        });

        CheckAssignmentButton.setBackground(new java.awt.Color(255, 255, 255));
        CheckAssignmentButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        CheckAssignmentButton.setForeground(new java.awt.Color(0, 0, 51));
        CheckAssignmentButton.setText("Check Assignments");
        CheckAssignmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAssignmentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(UploadSolutionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(UploadSolutionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UploadAssignmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(CheckAssignmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(UpperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckAssignmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UploadSolutionButton)
                    .addComponent(UploadAssignmentButton))
                .addGap(44, 44, 44)
                .addComponent(UploadSolutionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckAssignmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAssignmentButtonActionPerformed

        CheckAssignmentsPage check=new CheckAssignmentsPage();
        check.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CheckAssignmentButtonActionPerformed

    private void UploadSolutionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadSolutionButtonActionPerformed
        // TODO add your handling code here:
        UploadSolutionFrame uploadsolution=new UploadSolutionFrame();
        uploadsolution.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_UploadSolutionButtonActionPerformed

    private void UploadAssignmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadAssignmentButtonActionPerformed
        // TODO add your handling code here:
        TeacherUploadAssignments obj = new TeacherUploadAssignments();
        obj.setVisible(true);
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_UploadAssignmentButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:

        LoginFrame loginframe=new LoginFrame();
        loginframe.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    public void displaySubmittedAssignments()
    {
        DefaultTableModel Model=new DefaultTableModel(new String[]{"Assignment Id","Assignment Name","Student Id","Student Name"},0);
        ArrayList<StudentTeacher>TableEntries=LoginFrame.op.displayAssignmentTeacher();
        int assignmentId;
        String assignmentName;
        int studentId;
        String studentName;
        
        Iterator itr=TableEntries.iterator();
        
        while(itr.hasNext()){
           StudentTeacher obj=(StudentTeacher) itr.next();
           assignmentId=obj.assignmentId;
           assignmentName=obj.assignmentName;
           studentId=obj.studentId;
           studentName=obj.studentName;
           Model.addRow(new Object[]{assignmentId,assignmentName,studentId,studentName});
        }
       
        AssignmentListTable.setModel(Model);
        
        TableColumn col=AssignmentListTable.getColumnModel().getColumn(0);
        DefaultTableCellRenderer obj1=new DefaultTableCellHeaderRenderer();
        obj1.setHorizontalTextPosition(DefaultTableCellRenderer.CENTER);
        AssignmentListTable.getColumnModel().getColumn(0).setHeaderRenderer(obj1);
        
        col.setCellRenderer(obj1);
        
        TableColumn col1=AssignmentListTable.getColumnModel().getColumn(1);
        DefaultTableCellRenderer obj2=new DefaultTableCellHeaderRenderer();
        obj2.setHorizontalTextPosition(DefaultTableCellRenderer.CENTER);
        AssignmentListTable.getColumnModel().getColumn(1).setHeaderRenderer(obj2);
        col1.setCellRenderer(obj2);
        
        TableColumn col2=AssignmentListTable.getColumnModel().getColumn(2);
        DefaultTableCellRenderer obj3=new DefaultTableCellHeaderRenderer();
        obj3.setHorizontalTextPosition(DefaultTableCellRenderer.CENTER);
        AssignmentListTable.getColumnModel().getColumn(2).setHeaderRenderer(obj3);
        col2.setCellRenderer(obj3);
        
        TableColumn col3=AssignmentListTable.getColumnModel().getColumn(3);
        DefaultTableCellRenderer obj4=new DefaultTableCellHeaderRenderer();
        obj4.setHorizontalTextPosition(DefaultTableCellRenderer.CENTER);
        AssignmentListTable.getColumnModel().getColumn(3).setHeaderRenderer(obj4);
        col3.setCellRenderer(obj4);
        
        
    }
    
    public void displayTeacherInformation()
    {
        StudentTeacher obj = LoginFrame.op.getTeacherInformation(LoginFrame.teacherId);
        TeacherNameLabel.setText(LoginFrame.teacherId+"   "+obj.teacherName+"   "+obj.subjectName);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherLoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AssignmentListTable;
    private javax.swing.JButton CheckAssignmentButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel TeacherNameLabel;
    private javax.swing.JButton UploadAssignmentButton;
    private javax.swing.JButton UploadSolutionButton;
    private javax.swing.JPanel UploadSolutionPanel;
    private javax.swing.JPanel UpperPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
