
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aditiambadkar
 */
public class ViewAssignment extends javax.swing.JFrame {

    /**
     * Creates new form ViewAssignment
     */
    public ViewAssignment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel1 = new javax.swing.JPanel();
        UpperPanel1 = new javax.swing.JPanel();
        ViewSolutionLabel1 = new javax.swing.JLabel();
        LowerPanel = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        ViewButton = new javax.swing.JButton();
        AssignmentIdlabel = new javax.swing.JLabel();
        AssignmentIdTextArea = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AssignmentContent = new javax.swing.JTextArea();
        SubjectIdlabel = new javax.swing.JLabel();
        SubjectIdTextArea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel1.setBackground(new java.awt.Color(255, 255, 255));

        UpperPanel1.setBackground(new java.awt.Color(167, 167, 231));

        ViewSolutionLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        ViewSolutionLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ViewSolutionLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewSolutionLabel1.setText("View Assignments");

        javax.swing.GroupLayout UpperPanel1Layout = new javax.swing.GroupLayout(UpperPanel1);
        UpperPanel1.setLayout(UpperPanel1Layout);
        UpperPanel1Layout.setHorizontalGroup(
            UpperPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(ViewSolutionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        UpperPanel1Layout.setVerticalGroup(
            UpperPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ViewSolutionLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        LowerPanel.setBackground(new java.awt.Color(167, 167, 231));

        BackButton.setForeground(new java.awt.Color(0, 0, 0));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        ViewButton.setForeground(new java.awt.Color(0, 0, 0));
        ViewButton.setText("View");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LowerPanelLayout = new javax.swing.GroupLayout(LowerPanel);
        LowerPanel.setLayout(LowerPanelLayout);
        LowerPanelLayout.setHorizontalGroup(
            LowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LowerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221)
                .addComponent(ViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        LowerPanelLayout.setVerticalGroup(
            LowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(ViewButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        AssignmentIdlabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        AssignmentIdlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AssignmentIdlabel.setText("Enter Assignment ID:");

        AssignmentIdTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignmentIdTextAreaActionPerformed(evt);
            }
        });

        AssignmentContent.setColumns(20);
        AssignmentContent.setRows(5);
        jScrollPane1.setViewportView(AssignmentContent);

        SubjectIdlabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SubjectIdlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SubjectIdlabel.setText("Enter Subject ID:");

        SubjectIdTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectIdTextAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanel1Layout = new javax.swing.GroupLayout(MainPanel1);
        MainPanel1.setLayout(MainPanel1Layout);
        MainPanel1Layout.setHorizontalGroup(
            MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpperPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(MainPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPanel1Layout.createSequentialGroup()
                        .addComponent(SubjectIdlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SubjectIdTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanel1Layout.createSequentialGroup()
                        .addComponent(AssignmentIdlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AssignmentIdTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanel1Layout.setVerticalGroup(
            MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel1Layout.createSequentialGroup()
                .addComponent(UpperPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssignmentIdlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssignmentIdTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubjectIdlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubjectIdTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LowerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        AssignmentContent.setText("");
        StudentLoginPage studentlogin=new StudentLoginPage();
        studentlogin.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        // TODO add your handling code here:
        AssignmentContent.setText("");
        if(AssignmentIdTextArea.getText().isEmpty() || SubjectIdTextArea.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Fields cannot be empty!!","Error",JOptionPane.ERROR_MESSAGE);
            AssignmentIdTextArea.setText("");
            SubjectIdTextArea.setText("");
        }
        else
        {
            try{
                int flag=0;
                int assignmentId=Integer.parseInt(AssignmentIdTextArea.getText());
                int subjectId=Integer.parseInt(SubjectIdTextArea.getText());
                flag=LoginFrame.op.checkExistingAssignmentTeacher(assignmentId);
                if(flag==1){
                    String str=LoginFrame.op.viewAssignment(assignmentId,subjectId);
                    AssignmentContent.setText(str);
                    AssignmentContent.setLineWrap(true);
                    AssignmentContent.setWrapStyleWord(true);
                    AssignmentContent.setEditable(false);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Assignment does not exists!!","Error",JOptionPane.ERROR_MESSAGE);
                    AssignmentIdTextArea.setText("");
                    SubjectIdTextArea.setText("");
                    AssignmentContent.setText("");
                }
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this,"Assignment Id is numeric value!!","Error",JOptionPane.ERROR_MESSAGE);
                AssignmentIdTextArea.setText("");
                SubjectIdTextArea.setText("");
                AssignmentContent.setText("");
            }
        }
    }//GEN-LAST:event_ViewButtonActionPerformed

    private void AssignmentIdTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignmentIdTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssignmentIdTextAreaActionPerformed

    private void SubjectIdTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectIdTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectIdTextAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAssignment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AssignmentContent;
    private javax.swing.JTextField AssignmentIdTextArea;
    private javax.swing.JLabel AssignmentIdlabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel LowerPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MainPanel1;
    private javax.swing.JTextField SubjectIdTextArea;
    private javax.swing.JLabel SubjectIdlabel;
    private javax.swing.JPanel UpperPanel;
    private javax.swing.JPanel UpperPanel1;
    private javax.swing.JButton ViewButton;
    private javax.swing.JLabel ViewSolutionLabel;
    private javax.swing.JLabel ViewSolutionLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
